export const ROUTES = {
  app: "/app",
  dashboard: "/app",
  clientes: "/app/clientes",
  aparelhos: "/app/aparelhos",
  ordens: "/app/ordens",
  novaOS: "/app/ordens/nova",
  ordemDetalhe: (id: string) => `/app/ordens/${id}`,
  checklist: "/app/checklist",
  checklistOS: (ordemId: string) => `/app/checklist?ordemId=${ordemId}`,
  checklistSaida: (ordemId: string) => `/app/checklist?ordemId=${ordemId}&tipo=saida`,
  manutencao: "/app/manutencao",
  manutencaoOS: (ordemId: string) => `/app/manutencao?ordemId=${ordemId}`,
  orcamento: "/app/orcamento",
  orcamentoOS: (ordemId: string) => `/app/orcamento?ordemId=${ordemId}`,
  estoque: "/app/estoque",
  estoqueBaixo: "/app/estoque?filtro=baixo",
  movimentacoes: "/app/movimentacoes",
  pdv: "/app/pdv",
  financeiro: "/app/financeiro",
  despesas: "/app/despesas",
  atendimento: "/app/atendimento",
  usuarios: "/app/usuarios",
} as const;
